# Generated by Django 5.0 on 2023-12-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='employee_status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
