# Generated by Django 5.0 on 2023-12-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_age_useraccount_alternate_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
