# Generated by Django 5.0 on 2024-01-04 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccount_employee_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.department'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
