# Generated by Django 5.0 on 2024-01-04 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_useraccount_gender_product_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.department'),
            preserve_default=False,
        ),
    ]
