# Generated by Django 5.0 on 2024-01-04 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_designation_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_role',
        ),
        migrations.AlterField(
            model_name='designation',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department'),
        ),
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='employee_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.employee_status'),
        ),
        migrations.DeleteModel(
            name='User_role',
        ),
    ]
