# Generated by Django 5.0 on 2024-01-04 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_useraccount_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.designation'),
        ),
    ]
