# Generated by Django 5.0 on 2024-01-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_product_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.EmailField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
