# Generated by Django 5.0 on 2024-01-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_drp_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drp_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
