# Generated by Django 5.0 on 2024-01-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_drp_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Drp_Department',
        ),
    ]
