# Generated by Django 5.0 on 2024-01-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_useraccount_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
