# Generated by Django 5.0 on 2024-01-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_product_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='department',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='designation',
        ),
    ]
