# Generated by Django 5.0 on 2024-01-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_useraccount_department_designation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drp_Department',
            new_name='Department',
        ),
    ]
