# Generated by Django 5.0 on 2024-01-05 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_rename_drp_department_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='drp_product',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='department',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
        migrations.AddField(
            model_name='designation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drp_product',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department'),
        ),
        migrations.AddField(
            model_name='drp_product',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.designation'),
        ),
        migrations.AddField(
            model_name='drp_product',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='drp_Designation',
        ),
    ]
