# Generated by Django 5.0 on 2024-01-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_remove_designation_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('link_type', models.CharField(blank=True, default='', max_length=500)),
                ('user_link', models.CharField(blank=True, default='', max_length=500)),
                ('access_department', models.CharField(blank=True, default='', max_length=500)),
                ('table_ref', models.CharField(blank=True, default='', max_length=500)),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_links',
            field=models.ManyToManyField(to='account.user_links'),
        ),
    ]
