# Generated by Django 5.0 on 2024-01-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_user_links_useraccount_user_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_links',
        ),
        migrations.DeleteModel(
            name='user_links',
        ),
    ]
