# Generated by Django 5.0 on 2024-01-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_user_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_links',
        ),
    ]
