# Generated by Django 5.0 on 2024-01-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_user_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='employee_status',
            field=models.BooleanField(default=True),
        ),
    ]
