# Generated by Django 5.0 on 2024-03-05 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_remove_useraccount_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='employee_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.employee_status'),
        ),
    ]
