# Generated by Django 5.0.1 on 2024-03-05 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_useraccount_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='employee_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.employee_status'),
        ),
    ]
