# Generated by Django 5.0 on 2024-03-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_useraccount_employee_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drp_Product',
            new_name='Drp_Program',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Program',
        ),
        migrations.RenameField(
            model_name='drp_program',
            old_name='product',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='product',
            new_name='program',
        ),
    ]
