# Generated by Django 5.0.1 on 2024-03-26 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_rename_drp_product_drp_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='drp_program',
            name='sub_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.sub_program'),
        ),
    ]
