# Generated by Django 5.0.1 on 2024-03-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_sub_program_drp_program_sub_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_pwd_token',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
