# Generated by Django 5.0.1 on 2024-03-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_canned_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drp_program',
            name='program',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='program',
        ),
        migrations.RemoveField(
            model_name='drp_program',
            name='sub_program',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Sub_Program',
        ),
    ]
