# Generated by Django 5.0.1 on 2024-04-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_remove_drp_program_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
