# Generated by Django 5.0.1 on 2024-04-02 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_useraccount_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
