# Generated by Django 5.0.1 on 2024-04-02 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_useraccount_user_manager_alter_useraccount_director'),
        ('leads', '0043_rename_services_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='director',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user_manager',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.segment'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.service'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leaders_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
