# Generated by Django 5.0.1 on 2024-04-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_remove_useraccount_admin_and_more'),
        ('leads', '0043_rename_services_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='marketplace',
            field=models.ManyToManyField(to='leads.marketplace'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='program',
            field=models.ManyToManyField(to='leads.program'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='sub_program',
            field=models.ManyToManyField(to='leads.sub_program'),
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='service',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='service',
            field=models.ManyToManyField(to='leads.service'),
        ),
    ]
