# Generated by Django 5.0.1 on 2024-04-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_user_restore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='mouFile',
        ),
        migrations.DeleteModel(
            name='paymentProofFile',
        ),
    ]
