# Generated by Django 5.0.1 on 2024-05-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_delete_file_delete_moufile_delete_paymentprooffile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('notes', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='employee_leaves',
            field=models.ManyToManyField(to='account.employee_leaves'),
        ),
    ]
