# Generated by Django 5.0.1 on 2024-05-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_employee_leaves_useraccount_employee_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_leaves',
            name='notes',
            field=models.CharField(max_length=300),
        ),
    ]
