# Generated by Django 5.0.1 on 2024-05-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_alter_employee_leaves_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_leave_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
