# Generated by Django 5.0.1 on 2024-05-10 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_employee_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_leaves',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.employee_leave_status'),
        ),
    ]
