# Generated by Django 5.0.1 on 2024-05-10 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_alter_employee_leaves_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_leaves',
            name='employee',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='employee_leave', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='employee_leaves',
            field=models.ManyToManyField(related_name='user_accounts', to='account.employee_leaves'),
        ),
    ]
