# Generated by Django 5.0 on 2024-01-04 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_remove_useraccount_gender_product_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_turnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commercials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, default='', max_length=100)),
                ('commission', models.CharField(blank=True, default='', max_length=100)),
                ('price_for_mou', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drp_business_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drp_business_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drp_country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drp_firm_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='drp_lead_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Remark_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('marketplace', models.CharField(blank=True, default='', max_length=100)),
                ('Service_category', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drp_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.drp_country')),
            ],
        ),
        migrations.CreateModel(
            name='Drp_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.drp_state')),
            ],
        ),
        migrations.CreateModel(
            name='Followup_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('followup_time', models.CharField(blank=True, default='', max_length=100)),
                ('followup_notes', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, default='', max_length=100)),
                ('service_country', models.CharField(blank=True, default='', max_length=100)),
                ('marketplace', models.CharField(blank=True, default='', max_length=100)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('provider_id', models.CharField(blank=True, default='', max_length=100)),
                ('service_requester_type', models.CharField(blank=True, default='', max_length=100)),
                ('client_name', models.CharField(blank=True, default='', max_length=100)),
                ('requester_id', models.CharField(blank=True, default='', max_length=100)),
                ('email_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.CharField(blank=True, default='', max_length=100)),
                ('service_category', models.CharField(blank=True, default='', max_length=100)),
                ('requester_location', models.CharField(blank=True, default='', max_length=100)),
                ('requester_sell_in_country', models.CharField(blank=True, default='', max_length=100)),
                ('current_status', models.CharField(blank=True, default='', max_length=100)),
                ('hot_lead', models.CharField(blank=True, default='', max_length=100)),
                ('business_name', models.CharField(blank=True, default='', max_length=100)),
                ('brand_name', models.CharField(blank=True, default='', max_length=100)),
                ('name_for_mou', models.CharField(blank=True, default='', max_length=100)),
                ('designation_in_company', models.CharField(blank=True, default='', max_length=100)),
                ('monthly_sales', models.CharField(blank=True, default='', max_length=100)),
                ('gst', models.CharField(blank=True, default='', max_length=100)),
                ('address_line1', models.CharField(blank=True, default='', max_length=100)),
                ('address_line2', models.CharField(blank=True, default='', max_length=100)),
                ('pin_code', models.CharField(blank=True, default='', max_length=100)),
                ('email_record', models.CharField(blank=True, default='', max_length=100)),
                ('deadline', models.CharField(blank=True, default='', max_length=100)),
                ('seller_website', models.CharField(blank=True, default='', max_length=100)),
                ('amazon_store_link', models.CharField(blank=True, default='', max_length=100)),
                ('facebook_store_link', models.CharField(blank=True, default='', max_length=100)),
                ('instagram_store_link', models.CharField(blank=True, default='', max_length=100)),
                ('visibility', models.CharField(blank=True, default='', max_length=100)),
                ('associate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.drp_business_category')),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.drp_business_type')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.drp_city')),
                ('client_turnover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.client_turnover')),
                ('contact_preferences', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.contact_preference')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.drp_country')),
                ('firm_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.drp_firm_type')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.followup_history')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.drp_state')),
                ('remark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.remark_history')),
            ],
        ),
        migrations.CreateModel(
            name='email_ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(blank=True, default='', max_length=100)),
                ('lead_id', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
        ),
        migrations.CreateModel(
            name='Email_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('date', models.DateField()),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead_id', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(blank=True, default='', max_length=100)),
                ('lead_id', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
        ),
        migrations.CreateModel(
            name='contact_numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, default='', max_length=100)),
                ('contact_number_type', models.CharField(blank=True, default='', max_length=100)),
                ('lead_id', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_numbers', models.CharField(blank=True, default='', max_length=100)),
                ('lead_id', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
        ),
        migrations.CreateModel(
            name='Service_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.followup_history')),
                ('pricing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.commercials')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.product')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.drp_lead_status')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.services')),
            ],
        ),
        migrations.AddField(
            model_name='commercials',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.services'),
        ),
        migrations.CreateModel(
            name='Status_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField()),
                ('lead_id', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.drp_lead_status')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
