# Generated by Django 5.0 on 2024-01-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup_history',
            name='followup_date',
            field=models.DateField(default='0001/01/01'),
        ),
        migrations.AlterField(
            model_name='followup_history',
            name='followup_time',
            field=models.TimeField(),
        ),
    ]
