# Generated by Django 5.0 on 2024-01-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_followup_history_followup_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_number',
            old_name='contact_numbers',
            new_name='contact_number',
        ),
        migrations.DeleteModel(
            name='contact_numbers',
        ),
    ]
