# Generated by Django 5.0 on 2024-01-08 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_rename_contact_numbers_contact_number_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark_history',
            old_name='title',
            new_name='remark',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='remark',
        ),
        migrations.AddField(
            model_name='remark_history',
            name='lead_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leads'),
        ),
    ]
