# Generated by Django 5.0 on 2024-01-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_rename_title_remark_history_remark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='country',
        ),
    ]
