# Generated by Django 5.0 on 2024-01-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_services_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='Service_category',
            new_name='Service_name',
        ),
        migrations.RemoveField(
            model_name='service_category',
            name='product',
        ),
    ]
