# Generated by Django 5.0 on 2024-01-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_rename_service_category_services_service_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='email_id',
        ),
    ]
