# Generated by Django 5.0 on 2024-01-10 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_marketplace_remove_services_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='marketplace_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.marketplace'),
        ),
    ]
