# Generated by Django 5.0 on 2024-01-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_services_marketplace_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplace',
            name='service_id',
        ),
    ]
