# Generated by Django 5.0 on 2024-01-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_remove_marketplace_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='Service_name',
            new_name='service_name',
        ),
    ]
