# Generated by Django 5.0 on 2024-01-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_rename_service_name_services_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_id',
        ),
    ]
