# Generated by Django 5.0 on 2024-01-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_remove_services_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercials',
            name='marketplace_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.marketplace'),
        ),
    ]
