# Generated by Django 5.0 on 2024-01-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_commercials_marketplace_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='service_category',
        ),
    ]
