# Generated by Django 5.0 on 2024-01-10 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_remove_leads_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.service_category'),
        ),
    ]
