# Generated by Django 5.0 on 2024-01-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_leads_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercials',
            name='marketplace_id',
        ),
        migrations.RemoveField(
            model_name='service_category',
            name='pricing',
        ),
    ]
