# Generated by Django 5.0 on 2024-01-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_remove_commercials_marketplace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.commercials'),
        ),
    ]
