# Generated by Django 5.0 on 2024-01-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_remove_leads_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
