# Generated by Django 5.0 on 2024-01-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_leads_commercials_leads_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.status_history'),
        ),
    ]
