# Generated by Django 5.0 on 2024-01-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_alter_leads_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_ids',
            name='lead_id',
        ),
        migrations.AddField(
            model_name='leads',
            name='alternate_contact_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='leads',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Contact_number',
        ),
        migrations.DeleteModel(
            name='email_ids',
        ),
    ]
