# Generated by Django 5.0 on 2024-01-15 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_remove_email_ids_lead_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='alternate_email_id',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='leads',
            name='email_id',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.drp_lead_status'),
        ),
    ]
