# Generated by Django 5.0 on 2024-01-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_leads_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='created_at',
            new_name='upload_date',
        ),
    ]
