# Generated by Django 5.0 on 2024-01-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_turn_arround_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='monthly_sales',
        ),
    ]
