# Generated by Django 5.0 on 2024-01-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_remove_leads_deadline_remove_leads_monthly_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='service_country',
        ),
    ]
