# Generated by Django 5.0 on 2024-01-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_remove_leads_service_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup_history',
            name='followup_time',
        ),
        migrations.AlterField(
            model_name='followup_history',
            name='followup_date',
            field=models.DateTimeField(default='0001/01/01'),
        ),
    ]
