# Generated by Django 5.0 on 2024-01-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_remove_followup_history_followup_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercials',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='marketplace_id',
        ),
        migrations.AddField(
            model_name='marketplace',
            name='service',
            field=models.ManyToManyField(to='leads.services'),
        ),
        migrations.AddField(
            model_name='services',
            name='commercials',
            field=models.ManyToManyField(to='leads.commercials'),
        ),
    ]
