# Generated by Django 5.0 on 2024-03-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_commercials_visibility_marketplace_visibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('visibility', models.BooleanField(default=True)),
                ('marketplace', models.ManyToManyField(to='leads.marketplace')),
            ],
        ),
    ]
