# Generated by Django 5.0 on 2024-03-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(blank=True, default='', max_length=100)),
                ('visibility', models.BooleanField(default=True)),
                ('service', models.ManyToManyField(to='leads.services')),
            ],
        ),
    ]
