# Generated by Django 5.0 on 2024-03-17 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='commercials',
        ),
        migrations.RemoveField(
            model_name='services',
            name='commercials',
        ),
        migrations.RemoveField(
            model_name='marketplace',
            name='service',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='service_category',
        ),
        migrations.DeleteModel(
            name='Commercials',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
