# Generated by Django 5.0 on 2024-03-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0035_remove_leads_commercials_remove_services_commercials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, default='', max_length=100)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
    ]
