# Generated by Django 5.0 on 2024-03-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0036_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(blank=True, default='', max_length=100)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
    ]
