# Generated by Django 5.0 on 2024-03-19 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0038_rename_marketplace_program_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercials', models.CharField(max_length=100)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services_with_Commercials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.BooleanField(default=True)),
                ('commercials', models.ManyToManyField(to='leads.commercials')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.marketplace')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.program')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.segment')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.services')),
            ],
        ),
    ]
