# Generated by Django 5.0 on 2024-03-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0039_commercials_services_with_commercials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services_with_Commercials',
            new_name='Services_and_Commercials',
        ),
    ]
