# Generated by Django 5.0 on 2024-03-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0040_rename_services_with_commercials_services_and_commercials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_program', models.CharField(blank=True, default='', max_length=100)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='services_and_commercials',
            name='sub_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.sub_program'),
            preserve_default=False,
        ),
    ]
