# Generated by Django 5.0 on 2024-03-20 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0041_sub_program_services_and_commercials_sub_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_and_commercials',
            name='sub_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.sub_program'),
        ),
    ]
