# Generated by Django 5.0 on 2024-03-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0042_alter_services_and_commercials_sub_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='services_and_commercials',
            old_name='services',
            new_name='service',
        ),
    ]
