# Generated by Django 5.0.1 on 2024-04-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0044_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='service_category_all',
            field=models.ManyToManyField(to='leads.service_category'),
        ),
    ]
