# Generated by Django 5.0.1 on 2024-04-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0045_leads_service_category_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark_history',
            name='lead_id',
        ),
        migrations.AddField(
            model_name='leads',
            name='remark',
            field=models.ManyToManyField(to='leads.remark_history'),
        ),
    ]
