# Generated by Django 5.0.1 on 2024-04-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0047_remove_status_history_lead_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='associate',
        ),
    ]
