# Generated by Django 5.0.1 on 2024-04-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0050_service_category_payment_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='mou_approval',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
