# Generated by Django 5.0.1 on 2024-04-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0051_service_category_mou_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='commercial_approval',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
