# Generated by Django 5.0.1 on 2024-04-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0052_service_category_commercial_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_category',
            name='followup',
        ),
        migrations.AddField(
            model_name='service_category',
            name='followup',
            field=models.ManyToManyField(to='leads.followup_history'),
        ),
    ]
