# Generated by Django 5.0.1 on 2024-04-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0053_remove_service_category_followup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup_history',
            name='followup_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
