# Generated by Django 5.0.1 on 2024-04-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0054_followup_history_followup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup_history',
            name='followup_date',
            field=models.DateField(default='0001/01/01'),
        ),
    ]
