# Generated by Django 5.0.1 on 2024-04-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0056_remove_service_category_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_history',
            name='status_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
