# Generated by Django 5.0.1 on 2024-04-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0057_alter_status_history_status_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
