# Generated by Django 5.0.1 on 2024-04-18 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0058_proposal_email_delete_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal_email',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.service'),
        ),
    ]
