# Generated by Django 5.0 on 2024-04-19 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0060_commercial_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='commercial_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.commercial_approval'),
        ),
    ]
