# Generated by Django 5.0 on 2024-04-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0061_alter_service_category_commercial_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial_approval',
            name='associate',
        ),
    ]
