# Generated by Django 5.0 on 2024-04-19 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0001_initial'),
        ('leads', '0062_remove_commercial_approval_associate'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='not_interested_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.not_interested'),
        ),
        migrations.AddField(
            model_name='leads',
            name='unresponsive_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.unresponsive'),
        ),
    ]
