# Generated by Django 5.0 on 2024-04-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0064_remove_leads_not_interested_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='address_line1',
            new_name='seller_address',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='city',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='country',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='state',
        ),
    ]
