# Generated by Django 5.0 on 2024-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0065_rename_address_line1_leads_seller_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='seller_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
