# Generated by Django 5.0 on 2024-04-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0066_alter_leads_seller_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='lead_owner',
            field=models.BooleanField(default=True),
        ),
    ]
