# Generated by Django 5.0 on 2024-04-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0071_rename_drp_business_category_business_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='status_history_all',
            field=models.ManyToManyField(to='leads.status_history'),
        ),
    ]
