# Generated by Django 5.0 on 2024-04-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0072_service_category_status_history_all'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup_history',
            old_name='followup_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='followup_history',
            old_name='followup_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='followup_history',
            old_name='followup_time',
            new_name='time',
        ),
    ]
