# Generated by Django 5.0 on 2024-04-24 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0073_rename_followup_date_followup_history_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask_For_Detail_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.service')),
            ],
        ),
    ]
