# Generated by Django 5.0 on 2024-04-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0074_ask_for_detail_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ask_For_Detail_Email',
        ),
    ]
