# Generated by Django 5.0 on 2024-04-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0076_service_category_lead_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='lead_id',
            new_name='client_id',
        ),
    ]
