# Generated by Django 5.0 on 2024-04-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0077_rename_lead_id_leads_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='followup',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='status',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='status_history_all',
        ),
    ]
