# Generated by Django 5.0.1 on 2024-04-29 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0078_remove_leads_followup_remove_leads_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='leads',
            name='client_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.client_designation'),
        ),
    ]
