# Generated by Django 5.0.1 on 2024-04-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0079_client_designation_leads_client_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='mou',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/mou'),
        ),
        migrations.AddField(
            model_name='service_category',
            name='payment_proof',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/payment_proof'),
        ),
    ]
