# Generated by Django 5.0.1 on 2024-04-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0082_commercial_approval_approval_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='commercial_approval',
            name='approval_type',
        ),
    ]
