# Generated by Django 5.0.1 on 2024-04-30 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0083_approval_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial_approval',
            name='approval_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.approval_type'),
        ),
    ]
