# Generated by Django 5.0.1 on 2024-05-02 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0002_approval_status'),
        ('leads', '0084_commercial_approval_approval_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial_approval',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.approval_status'),
        ),
    ]
