# Generated by Django 5.0.1 on 2024-05-02 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0002_approval_status'),
        ('leads', '0085_alter_commercial_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='payment_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.approval_status'),
        ),
    ]
