# Generated by Django 5.0.1 on 2024-05-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0087_service_category_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='subscription_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
