# Generated by Django 5.0.1 on 2024-05-03 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0089_subscription_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='subscription_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.subscription_type'),
        ),
    ]
