# Generated by Django 5.0.1 on 2024-05-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0092_commercials_lead_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercials',
            name='lead_id',
        ),
        migrations.AddField(
            model_name='commercials',
            name='lead_id',
            field=models.ManyToManyField(to='leads.service_category'),
        ),
    ]
