# Generated by Django 5.0 on 2023-12-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_basic_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_basic',
            name='age',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='date_of_birth',
            field=models.DateField(blank=True, default='0001-01-01'),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='disability',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='email_id',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='emergency_contact_number',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='employee_status',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employee_basic',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
