# Generated by Django 5.0 on 2023-12-13 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_identifiers',
            name='lead_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business_leads.all_identifiers'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='lead_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business_leads.all_identifiers'),
        ),
        migrations.AlterField(
            model_name='contact_preference',
            name='lead_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business_leads.all_identifiers'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='lead_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business_leads.all_identifiers'),
        ),
        migrations.AlterField(
            model_name='seller_address',
            name='lead_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business_leads.all_identifiers'),
        ),
        migrations.AlterField(
            model_name='service',
            name='lead_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business_leads.all_identifiers'),
        ),
        migrations.AlterField(
            model_name='website_store',
            name='lead_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business_leads.all_identifiers'),
        ),
    ]
