# Generated by Django 5.0 on 2023-12-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_leads', '0004_alter_business_identifiers_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='lead_status',
            field=models.CharField(blank=True, default='yet to contact', max_length=50),
        ),
    ]
