# Generated by Django 5.0 on 2023-12-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_leads', '0005_alter_service_lead_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_preference',
            old_name='contact_preference',
            new_name='contact_preferences',
        ),
    ]
