# Generated by Django 5.0 on 2023-12-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_leads', '0007_remove_contact_preference_lead_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_preference',
        ),
    ]
