# Generated by Django 5.0 on 2023-12-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_leads', '0011_contact_preference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_preference',
        ),
    ]
