# Generated by Django 5.0 on 2023-12-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_leads', '0012_delete_contact_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_preferences', models.CharField(blank=True, default='', max_length=500)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business_leads.all_identifiers')),
            ],
        ),
    ]
