# Generated by Django 5.0 on 2023-12-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_leads', '0014_all_identifiers_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_identifiers',
            name='country',
        ),
    ]
