# Generated by Django 5.0 on 2023-12-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_leads', '0018_alter_business_identifiers_lead_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='associate_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
