# Generated by Django 5.0 on 2023-12-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_leads', '0020_alter_service_associate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='associate_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
