# Generated by Django 5.0 on 2023-12-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_leads', '0022_alter_service_associate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='lead_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
