# Generated by Django 5.0 on 2023-12-26 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_leads', '0029_alter_service_associate_id_alter_service_lead_status'),
        ('dropdown', '0019_sup_designations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='lead_status',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='dropdown.lead_status'),
        ),
    ]
