# Generated by Django 5.0 on 2023-12-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_leads', '0030_alter_service_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_identifiers',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
