# Generated by Django 5.0.1 on 2024-04-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ev_bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200, null=True)),
                ('bank_name', models.CharField(max_length=500, null=True)),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('ifsc', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
