# Generated by Django 5.0 on 2023-12-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evitamin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ev_bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200, null=True)),
                ('bank_name', models.CharField(max_length=500, null=True)),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('ifsc', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ev_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=300)),
                ('marketplace', models.CharField(blank=True, default='', max_length=300)),
                ('services', models.CharField(blank=True, default='', max_length=300)),
                ('slab', models.CharField(blank=True, default='', max_length=300)),
                ('static_service_fees', models.CharField(blank=True, default='', max_length=300)),
                ('percentage_service_fees', models.CharField(blank=True, default='', max_length=300)),
                ('service_currency', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
