# Generated by Django 5.0 on 2023-12-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evitamin', '0002_ev_bank_details_ev_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_ask_for_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200, null=True)),
                ('email', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='email_service_proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, null=True)),
                ('marketplace', models.CharField(max_length=500, null=True)),
                ('service', models.CharField(max_length=200, null=True)),
                ('proposal_email', models.TextField(null=True)),
            ],
        ),
    ]
