# Generated by Django 5.0 on 2023-12-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evitamin', '0004_rename_slab_ev_services_price_for_mou'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ev_services',
            old_name='percentage_service_fees',
            new_name='commission_service_fees',
        ),
        migrations.AddField(
            model_name='ev_services',
            name='commission_price',
            field=models.BooleanField(default=False),
        ),
    ]
