# Generated by Django 5.0 on 2023-12-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evitamin', '0006_rename_commission_price_ev_services_commission_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='ev_services',
            name='service_id',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
