# Generated by Django 5.0 on 2023-12-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evitamin', '0007_ev_services_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ev_services',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
