# Generated by Django 4.2.6 on 2023-12-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xsup_drp_business_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_drp_contact_preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_drp_decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_drp_dropdown_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropdown_fields', models.CharField(max_length=500, null=True)),
                ('ref_tb', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_drp_firm_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_drp_gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_drp_lead_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_drp_not_interested_reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_drp_service_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_drp_service_country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_drp_unresponsive_reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_drp_user_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_email_ask_for_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200, null=True)),
                ('email', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_email_service_proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, null=True)),
                ('marketplace', models.CharField(max_length=500, null=True)),
                ('service', models.CharField(max_length=200, null=True)),
                ('proposal_email', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_ev_bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200, null=True)),
                ('bank_name', models.CharField(max_length=500, null=True)),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('ifsc', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_ev_branch_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_ev_department_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('designation', models.CharField(max_length=200, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_ev_employee_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_ev_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('created_by', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_ev_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=300, null=True)),
                ('marketplace', models.CharField(max_length=300, null=True)),
                ('services', models.CharField(max_length=300, null=True)),
                ('slab', models.CharField(max_length=300, null=True)),
                ('static_service_fees', models.CharField(max_length=300, null=True)),
                ('percentage_service_fees', models.CharField(max_length=300, null=True)),
                ('service_currency', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_image_src',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('src', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_list_business_leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=500, null=True)),
                ('table_type', models.CharField(max_length=500, null=True)),
                ('table_atr', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_list_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=500, null=True)),
                ('table_type', models.CharField(max_length=500, null=True)),
                ('table_atr', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_list_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=500, null=True)),
                ('table_type', models.CharField(max_length=500, null=True)),
                ('table_atr', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xsup_user_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('link_type', models.CharField(max_length=500, null=True)),
                ('user_link', models.CharField(max_length=500, null=True)),
                ('access_department', models.CharField(max_length=500, null=True)),
                ('table_ref', models.CharField(max_length=500, null=True)),
                ('link_status', models.BooleanField(default=False)),
            ],
        ),
    ]
