# Generated by Django 4.2.6 on 2023-12-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0002_rename_xsup_drp_business_type_business_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='email_ask_for_details',
        ),
        migrations.DeleteModel(
            name='email_service_proposal',
        ),
    ]
