# Generated by Django 5.0 on 2023-12-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0005_delete_ev_department_designation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ev_branch_location',
        ),
        migrations.DeleteModel(
            name='ev_products',
        ),
    ]
