# Generated by Django 5.0 on 2023-12-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0007_delete_ev_bank_details_delete_ev_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_business_leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=500, null=True)),
                ('table_type', models.CharField(max_length=500, null=True)),
                ('table_atr', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
