# Generated by Django 5.0 on 2023-12-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0009_alter_list_business_leads_table_atr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ev_commercials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=500, null=True)),
                ('service_country', models.CharField(max_length=200, null=True)),
                ('service_category', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
