# Generated by Django 5.0 on 2023-12-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0010_ev_commercials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_preference',
            new_name='contact_preference_list',
        ),
    ]
