# Generated by Django 5.0 on 2023-12-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0012_alter_business_type_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropdown_fields',
            old_name='dropdown_fields',
            new_name='title',
        ),
    ]
