# Generated by Django 5.0 on 2023-12-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0014_prop_dir_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_category_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
