# Generated by Django 5.0 on 2023-12-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0016_rename_user_role_user_role_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='country_state_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=500)),
                ('state', models.CharField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
