# Generated by Django 5.0 on 2023-12-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0020_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department',
            new_name='ev_department',
        ),
    ]
