# Generated by Django 5.0 on 2023-12-26 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0021_rename_department_ev_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ev_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deparment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdown.ev_department')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdown.sup_designations')),
            ],
        ),
    ]
