# Generated by Django 5.0 on 2023-12-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0022_ev_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_role_list',
            name='designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dropdown.ev_designation'),
            preserve_default=False,
        ),
    ]
