# Generated by Django 5.0 on 2023-12-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0023_user_role_list_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ev_designation',
            old_name='deparment',
            new_name='department',
        ),
    ]
