# Generated by Django 5.0 on 2023-12-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0024_rename_deparment_ev_designation_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_role_list',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dropdown.ev_department'),
            preserve_default=False,
        ),
    ]
