# Generated by Django 5.0 on 2023-12-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0026_rename_title_country_state_city_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country_state_city',
            old_name='country',
            new_name='title',
        ),
    ]
