# Generated by Django 5.0 on 2023-12-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_leads', '0014_all_identifiers_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='lead_delete_approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.BooleanField(default=False)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business_leads.all_identifiers')),
            ],
        ),
    ]
